export const PROD = [
  {
    id: 1,
    name: "Dulce de Leche",
    price: 850,
    category: "clasicos",
    description: "Cremoso helado de dulce de leche artesanal argentino.",
  },
  {
    id: 2,
    name: "Chocolate Amargo",
    price: 900,
    category: "clasicos",
    description: "Intenso chocolate belga con 70% de cacao.",
  },
  {
    id: 3,
    name: "Vainilla",
    price: 800,
    category: "clasicos",
    description: "Helado de vainilla natural con chaucha de Madagascar.",
  },
  {
    id: 4,
    name: "Frutilla",
    price: 950,
    category: "frutales",
    description: "Helado de frutillas frescas de temporada.",
  },
  {
    id: 5,
    name: "Limón",
    price: 820,
    category: "frutales",
    description: "Refrescante helado de limón con trozos de ralladura.",
  },
  {
    id: 6,
    name: "Maracuyá",
    price: 1100,
    category: "frutales",
    description: "Exótico helado de maracuyá con pulpa natural.",
  },
  {
    id: 7,
    name: "Mango",
    price: 1050,
    category: "frutales",
    description: "Helado tropical de mango fresco y cremoso.",
  },
  {
    id: 8,
    name: "Pistacho",
    price: 1200,
    category: "premium",
    description: "Helado premium de pistacho siciliano auténtico.",
  },
  {
    id: 9,
    name: "Tiramisú",
    price: 1150,
    category: "premium",
    description: "Inspirado en el clásico postre italiano con café y mascarpone.",
  },
  {
    id: 10,
    name: "Brownie con Nueces",
    price: 1000,
    category: "premium",
    description: "Chocolate con trozos de brownie y nueces pecanas.",
  },
  {
    id: 11,
    name: "Cookies & Cream",
    price: 950,
    category: "clasicos",
    description: "Vainilla con trozos generosos de galletas Oreo.",
  },
  {
    id: 12,
    name: "Menta Granizada",
    price: 880,
    category: "clasicos",
    description: "Refrescante menta con chips de chocolate.",
  },
  {
    id: 13,
    name: "Frambuesa",
    price: 1080,
    category: "frutales",
    description: "Helado de frambuesas con semillas naturales.",
  },
  {
    id: 14,
    name: "Coco Vegano",
    price: 920,
    category: "veganos",
    description: "Base de leche de coco, 100% vegano y sin lactosa.",
  },
  {
    id: 15,
    name: "Chocolate Vegano",
    price: 950,
    category: "veganos",
    description: "Chocolate intenso con base de leche de almendras.",
  },
  {
    id: 16,
    name: "Frutilla Vegana",
    price: 980,
    category: "veganos",
    description: "Helado vegano de frutillas con base de anacardos.",
  },
  {
    id: 17,
    name: "Sambayón",
    price: 1100,
    category: "premium",
    description: "Tradicional sambayón con vino Marsala italiano.",
  },
  {
    id: 18,
    name: "Marroc",
    price: 1250,
    category: "premium",
    description: "Chocolate suizo con almendras tostadas y miel.",
  },
  {
    id: 19,
    name: "Café Irlandés",
    price: 1180,
    category: "premium",
    description: "Café expreso con whisky y crema batida.",
  },
  {
    id: 20,
    name: "Cheesecake de Frutos Rojos",
    price: 1300,
    category: "especiales",
    description: "Helado de cheesecake con salsa de frutos rojos.",
  },
  {
    id: 21,
    name: "Ferrero Rocher",
    price: 1350,
    category: "especiales",
    description: "Avellanas, chocolate y wafer inspirado en el bombón.",
  },
  {
    id: 22,
    name: "Dulce de Leche Granizado",
    price: 1000,
    category: "especiales",
    description: "Dulce de leche con chips crocantes de chocolate.",
  },
];


export const CATEGORIES = [
  { id: "todos", label: "Todos" },
  { id: "clasicos", label: "Clásicos" },
  { id: "frutales", label: "Frutales" },
  { id: "premium", label: "Premium" },
  { id: "veganos", label: "Veganos" },
  { id: "especiales", label: "Especiales" },
];