export const PROD = [
    {
      id: 1,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 2,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 3,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 4,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 5,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 6,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 7,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 8,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 9,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 10,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 11,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 12,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 13,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 14,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 15,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 16,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 17,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 18,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 19,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 20,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 21,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
    {
      id: 22,
      name: "Nombre Producto",
      price: "00,00",
      description: "Rich chocolate ice cream with chunks of brownie.",
    },
  ];
